variables:
- group: common
- template: /.azuredevops/variables-global.yml

parameters:
- name: checkoutRef
  type: string
  default: develop

resources:
  repositories:
  - repository: pipelines_repo
    type: github
    endpoint: ROCm
    name: ROCm/ROCm
  - repository: release_repo
    type: github
    endpoint: ROCm
    name: ROCm/hipBLAS-common
    ref: ${{ parameters.checkoutRef }}

trigger: none
pr: none

jobs:
  - template: ${{ variables.CI_COMPONENT_PATH }}/hipBLAS-common.yml
    parameters:
      checkoutRepo: release_repo
      checkoutRef: ${{ parameters.checkoutRef }}
